spring.application.name=freelance-hub

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/freelance_hub}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:freelance_hub}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:freelance_hub_dev}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
